services:
  redis:
    image: redis:7-alpine
    container_name: qls_redis
    ports:
      - "127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - qls_redis_data:/data

volumes:
  qls_redis_data:
